// Fortune cookie messages
// Note: These are encrypted in the client to make it harder to view all fortunes at once

export const rawFortunes = [
  "A pigeon will eye your sandwich today. Stand strong.",
  "You will find a sock, but it won't match any others you own.",
  "A stranger will compliment your shoes. Wear your fanciest pair.",
  "The stars say today is a great day… for snacks.",
  "Someone will ask you a question, and your answer will surprise even you.",
  "Your favorite song is about to play. Turn up the volume.",
  "A typo you make will lead to a hilarious misunderstanding.",
  "Beware of ice cream that looks too perfect.",
  "You'll laugh at the same meme twice today.",
  "A cat will cross your path. It may or may not be lucky.",
  "You are one good decision away from a fantastic day.",
  "Keep going. Future-you is cheering you on.",
  "Your ideas are worth sharing—don't hold back.",
  "Big things often start with small, bold steps.",
  "The journey is more important than the speed.",
  "Something you've been waiting for is closer than you think.",
  "Take a leap of faith today. The net will appear.",
  "Progress, not perfection, will take you far.",
  "You've got this. And if you don't, you'll figure it out.",
  "The best version of you is already inside—let it shine.",
  "You'll accidentally say 'you too' when someone says, 'Happy Birthday.'",
  "A bird will sing directly to you today. Or at least it'll feel like it.",
  "A random object in your home will seem suspiciously out of place.",
  "Someone will explain something to you as if you don't already know it. Nod wisely.",
  "You will discover the joy of folding laundry… for 30 seconds.",
  "A meeting you attend will start late, but no one will acknowledge it.",
  "Someone you know will say, 'What's for dinner?' and expect you to know.",
  "You will find a snack in your bag that you forgot was there. Celebrate this.",
  "A YouTube rabbit hole awaits you this evening. Choose wisely.",
  "The answer to your question is: '42.'",
  "An exciting opportunity is coming your way.",
  "A loyal friend will bring you unexpected joy.",
  "Today's efforts will lead to tomorrow's rewards.",
  "Good news will arrive when you least expect it.",
  "Your kindness will inspire someone today.",
  "A small act of courage will make a big difference.",
  "A smile is your secret weapon today—use it often.",
  "Happiness is not a destination; it's the journey.",
  "The harder you work, the luckier you'll get.",
  "Your perseverance is about to pay off.",
  "A squirrel is judging you. Don't take it personally.",
  "Someone nearby will sneeze twice. Bless them generously.",
  "A mysterious package will arrive today—it's called 'your mail.'",
  "Beware of the color orange today. No reason, just vibes.",
  "A cup of coffee will give you more than caffeine—it'll give you hope.",
  "Your inbox will finally reach 'inbox zero.' Relish the moment.",
  "You will lose a pen today, but it'll reappear next week.",
  "Someone will call you by the wrong name. Roll with it.",
  "Your next snack will be legendary. Choose wisely.",
  "An unexpected delay will save you from a bigger inconvenience.",
  "An old song will bring back fond memories today.",
  "Your intuition will surprise you—it's sharper than you think.",
  "A compliment you give will make someone's day.",
  "The universe has a surprise for you. It's small but delightful.",
  "A fortune cookie a day keeps the bad vibes away. Keep it up!",
  "Today is a great day to start something small but meaningful.",
  "A tiny mistake will lead to an amusing story. Enjoy it.",
  "Your next dream will feature a cameo from a celebrity. Stay tuned.",
  "Beware of people who say, 'Trust me.' Proceed with caution.",
  "An unexpected message will brighten your day.",
  "You'll discover a new favorite food this week.",
  "Your next big idea will come while you're in the shower.",
  "Someone will ask you for advice and actually listen to it.",
  "A happy accident will lead to a fun discovery.",
  "The stars align for you today—metaphorically, not literally.",
  "A small act of kindness will come back to you tenfold.",
  "You will find joy in the little things today. Look closely.",
  "An old friend will resurface, bringing good vibes.",
  "Today, you are exactly where you need to be. Trust the timing.",
  "You'll realize something you thought was lost is still within you.",
  "A fun coincidence will make you smile today.",
  "Your bravery will inspire someone silently watching you.",
  "Take a deep breath. Clarity is closer than you think.",
  "The most exciting journeys begin with an uncertain step.",
  "Your sense of humor will defuse an awkward situation today.",
  "You are a magnet for good vibes today. Enjoy it.",
  "A small surprise will remind you that life is unpredictable.",
  "Someone will look to you for leadership—step up confidently.",
  "You will encounter a pun so bad, it's actually good.",
  "Laughter is contagious, and you're about to spread it.",
  "Be curious today. It will lead to something unexpected.",
  "A tiny moment of joy will have a ripple effect. Savor it.",
  "You will find strength in unexpected places today.",
  "Your upcoming sneeze will feel oddly satisfying.",
  "The next item you misplace will show up in the most unexpected spot.",
  "You will master the art of opening jars this week.",
  "Someone will make you laugh so hard, you’ll cry a little.",
  "Your next coffee will taste like pure magic.",
  "A joke you tell today will land perfectly. Savor it.",
  "You’ll find a receipt and wonder why you kept it.",
  "Someone will call you 'buddy.' Take it as a compliment.",
  "An animal will stare at you with curiosity today.",
  "You’ll get the sudden urge to organize your desk. Follow it.",
  "The best part of your day hasn’t happened yet.",
  "You’re about to discover a shortcut that changes everything.",
  "Your next attempt at cooking will yield surprisingly good results.",
  "Someone will think of you fondly today.",
  "A mystery you’ve been pondering will finally make sense.",
  "Your next impulse decision will be surprisingly great.",
  "An unexpected compliment will brighten your day.",
  "You’ll find humor in a frustrating situation.",
  "You will inspire someone without even realizing it.",
  "A random act of kindness will restore your faith in humanity.",
  "You’ll stumble upon something you didn’t know you needed.",
  "Your next outfit choice will feel like a power move.",
  "A long-forgotten memory will resurface and make you smile.",
  "Today, you will impress someone with your wit.",
  "You’re about to learn something new that excites you.",
  "The best ideas often arrive when you’re least expecting them.",
  "An unexpected connection will lead to something amazing.",
  "You’re going to laugh at something you really shouldn’t.",
  "Someone will send you a meme that speaks to your soul.",
  "The next person you text will bring you good vibes.",
  "You will discover the joy of doing absolutely nothing for five minutes.",
  "Your dance moves will impress an imaginary audience today.",
  "You’ll hear an oddly specific piece of advice. It will resonate.",
  "You’ll find a moment of peace where you least expect it.",
  "An error in your favor will leave you pleasantly surprised.",
  "Someone nearby will hiccup. Offer them a kind smile.",
  "The weather will align perfectly with your mood today.",
  "A random smell will transport you to a childhood memory.",
  "You’re about to hear a compliment that will stick with you.",
  "Your next adventure starts with a small detour.",
  "The stars say this is a great day to pet a dog.",
  "Someone will say something that makes you rethink your assumptions.",
  "You’ll witness an oddly heartwarming moment today.",
  "Your playlist is about to deliver the perfect vibe.",
  "You’ll rediscover the simple joy of opening a window.",
  "Your next online purchase will bring unexpected delight.",
  "Someone will look at you with admiration today. Smile back.",
  "You’ll overhear a conversation that makes you chuckle.",
  "An odd coincidence will make you believe in serendipity.",
  "Your next stretch will feel like the best one of your life.",
  "You will find beauty in something ordinary today.",
  "A chance encounter will leave a lasting impression.",
  "Today’s mistake will become tomorrow’s funny story.",
  "You’ll realize the power of a well-timed pause today.",
  "Your favorite beverage will taste extra good this week.",
  "A bird will sing a song that feels like it’s just for you.",
  "You’ll learn a new word that perfectly describes something in your life.",
  "Someone will send you a text that makes your day.",
  "The next pen you grab will write perfectly on the first try.",
  "You’ll find an old photo and smile at how far you’ve come.",
  "An unexpected compliment will make you feel seen.",
  "You’ll find the courage to speak up when it matters most.",
  "Someone will thank you sincerely, and it will warm your heart.",
  "Your next decision will feel like the right one. Trust it.",
  "A little patience will go a long way today.",
  "A simple question will spark a meaningful conversation.",
  "You’re about to discover a hidden talent. Be open to it.",
  "An old song will bring back a wave of nostalgia today.",
  "Your next mistake will lead to an important lesson.",
  "You’ll realize today that you’re capable of more than you thought.",
  "An unexpected act of kindness will come your way.",
  "The color blue will catch your attention today. Enjoy its calmness.",
  "You’ll discover the joy of a quiet moment in nature.",
  "A warm beverage will soothe your soul today.",
  "You’ll notice something you’ve been taking for granted. Appreciate it.",
  "A small breakthrough will lead to big progress soon.",
  "The next time you smile, it will be contagious.",
  "A simple truth will hit you hard today. Embrace it.",
  "You’re about to turn an ordinary moment into something special.",
  "Someone you admire will compliment you. Accept it graciously.",
  "Your next big laugh is closer than you think.",
  "You’ll find yourself humming a song that makes you happy.",
  "A small change you make today will have a big impact later.",
  "Your instincts will guide you well today. Follow them.",
  "A bright idea will come to you at the perfect time.",
  "An unexpected favor will be done for you today. Pay it forward.",
  "You’ll notice beauty in a place you’ve overlooked before.",
  "A casual conversation will leave a lasting impression.",
  "Your efforts today will pay off in unexpected ways.",
  "The stars say this is a great day to try something new.",
  "A little laughter will go a long way today. Don’t hold back.",
  "Someone will tell you a story that changes your perspective.",
  "You’re about to find inspiration in the most unlikely place.",
  "A burst of creativity will lead to something wonderful.",
  "You’ll discover that your patience is stronger than you thought.",
  "You’ll find a penny today. Pick it up, and the luck will follow.",
  "The next dog you see will make you smile.",
  "A kind word you say will ripple further than you think.",
  "Someone will ask for your advice. Trust yourself to give it.",
  "You’re going to hear a laugh today that’s absolutely infectious.",
  "An unexpected delay will actually work in your favor.",
  "You’ll rediscover the joy of doodling during a quiet moment.",
  "A sweet aroma will remind you of a happy memory.",
  "You’ll find a shortcut that saves you time today.",
  "A random stranger will compliment your taste in music.",
  "Your next sip of water will be oddly refreshing.",
  "A conversation today will spark a surprising idea.",
  "You’ll notice a subtle kindness from someone close to you.",
  "You’ll hear a joke so bad it’s brilliant.",
  "The sky will put on a show for you today—take a moment to look up.",
  "A soft blanket will feel extra cozy tonight.",
  "You’ll find joy in completing a simple task today.",
  "An unusual cloud will catch your attention—daydream for a while.",
  "A song you forgot about will resurface and lift your mood.",
  "You’ll wake up tomorrow feeling more refreshed than usual.",
  "A thoughtful gesture will remind you how connected we all are.",
  "You’ll meet someone who surprises you in the best way.",
  "A small win today will feel much bigger than expected.",
  "Your next bite of food will be pure bliss.",
  "The sound of rain will soothe you today, even if only in memory.",
  "A small challenge today will make you feel accomplished.",
  "You’ll overhear a heartwarming story that sticks with you.",
  "An old book will catch your eye—flip through it.",
  "A spontaneous idea will lead to a memorable moment.",
  "You’ll notice a hidden detail in something you’ve seen a hundred times.",
  "A message from the past will remind you how far you’ve come.",
  "You’ll realize you’re stronger than you thought today.",
  "Someone will go out of their way to make you smile.",
  "You’ll find inspiration in the most unexpected place today.",
  "Your next step will feel lighter than usual—enjoy it.",
  "A new opportunity is just around the corner. Be ready.",
  "Your creativity will shine bright today—let it flow.",
  "A small act of generosity will create big ripples.",
  "You’ll laugh so hard today that you’ll forget why you started laughing.",
  "A small favor you ask for will be granted happily.",
  "A gentle breeze will carry a sense of calm your way.",
  "The next thing you misplace will be exactly where you left it.",
  "You’ll realize you’re exactly where you’re meant to be today.",
  "A sudden burst of energy will push you toward something great.",
  "Your next small risk will bring a big reward.",
  "A funny coincidence will brighten your day.",
  "A friend will share something with you that warms your heart.",
  "Your next cup of tea (or coffee) will feel extra comforting.",
  "An ordinary object will seem extraordinary when you look closely.",
  "You’ll hear a phrase that sticks with you for days.",
  "A delicious smell will fill the air and bring back memories.",
  "You’re about to impress yourself with your problem-solving skills.",
  "The stars say this is a great day to let loose and dance.",
  "A happy accident will remind you that things happen for a reason.",
  "Your next hug will feel like a recharge. Seek it out.",
  "You’ll have a chance to make someone’s day—take it.",
  "You’ll rediscover the joy of an old hobby today.",
  "A witty remark you make will leave everyone laughing.",
  "The next breeze you feel will carry good vibes your way.",
  "A small surprise is waiting for you around the corner.",
  "You’ll reconnect with someone who’s been on your mind lately.",
  "Your next nap will feel like the best decision you’ve made all week.",
  "Someone will share a secret with you—handle it with care.",
  "The stars say this is a great day for reflection. Take a moment.",
  "A simple gesture will remind you of the goodness in people.",
  "You’ll witness a random act of kindness that inspires you.",
  "The next compliment you receive will stick with you for weeks.",
  "You’ll find beauty in the most unexpected place today.",
  "An old piece of advice will suddenly make sense.",
  "You’ll accomplish something today that feels like a small miracle.",
  "The stars suggest you treat yourself today. Don’t resist.",
  "You’ll realize you’ve grown more than you thought in the past year.",
  "Your next decision will bring unexpected clarity.",
  "A photo you take today will become one of your favorites.",
  "You’ll find joy in the rhythm of a repetitive task today.",
  "An unexpected gift will make you smile soon.",
  "Your next big laugh will come from something completely random.",
  "You’ll find courage in the quietest moment today.",
  "The next person you greet will surprise you with kindness.",
  "A colorful moment will brighten your day—don’t miss it.",
  "Your next detour will lead to something wonderful.",
  "You’ll rediscover the joy of looking at the stars tonight.",
  "A handwritten note will feel extra special today.",
  "Your instincts will guide you to something remarkable soon.",
  "A chance meeting will leave you with a story to tell.",
  "You’ll realize today how much someone appreciates you.",
  "The next sound you hear will bring you a surprising sense of peace.",
  "A childhood memory will bubble up and make you smile.",
  "You’re about to create something you’re proud of.",
  "A small, unexpected change will set your day on a brighter path.",
  "Your curiosity today will lead to a delightful discovery.",
  "A friend will say something today that stays with you forever.",
  "Your next laugh will be so genuine it surprises even you.",
  "The universe is conspiring to bring you a moment of peace today.",
  "The color green will bring you joy today. Seek it out.",
  "Your next handshake will feel oddly meaningful.",
  "You’ll smile at a stranger today, and it will make their day.",
  "The next cloud you see will resemble something familiar.",
  "You’ll discover a shortcut that saves you at least five minutes.",
  "An unexpected playlist will fit your mood perfectly.",
  "A breeze will carry a scent that reminds you of home.",
  "You’ll have a moment of deja vu that feels oddly comforting.",
  "A nostalgic photo will spark a beautiful memory today.",
  "Someone will notice the effort you’ve put in lately. Take the compliment.",
  "The next door you walk through will lead to something good.",
  "You’ll make a clever joke today that gets genuine laughs.",
  "The stars say this is a great day to find balance. Take a deep breath.",
  "You’ll spot something small that fills you with gratitude.",
  "The next step you take will lead you closer to your dreams.",
  "You’ll learn a new fact today that fascinates you.",
  "Your next meal will feel like a tiny celebration.",
  "A simple song lyric will stick with you all day in the best way.",
  "A funny coincidence will remind you of life’s sense of humor.",
  "Your patience will pay off sooner than you think.",
  "Someone will tell you a story that leaves you inspired.",
  "You’ll solve a puzzle today—maybe literal, maybe metaphorical.",
  "A small success today will boost your confidence.",
  "You’ll reconnect with something you love but haven’t done in a while.",
  "An unexpected pause will give you a moment of clarity.",
  "Your next laugh will feel like the best medicine.",
  "You’ll notice a color today that lifts your spirits.",
  "A creative spark will lead you to something exciting.",
  "You’ll find peace in a moment of stillness today.",
  "The next kind word you say will have a bigger impact than you realize.",
  "You’ll witness an act of teamwork that inspires you.",
  "An unlikely source will bring you joy today.",
  "The stars say today is a great day to embrace the unexpected.",
  "You’ll discover an old object that sparks a fresh idea.",
  "Your resilience will shine through in an unexpected way today.",
  "A light drizzle will feel like a welcome refresh. Enjoy it.",
  "You’ll hear laughter that makes your own smile inevitable.",
  "A small detail will make something ordinary feel extraordinary today.",
  "Your next compliment will catch someone off guard—in a good way.",
  "An overlooked moment will suddenly hold great meaning.",
  "A mistake today will teach you something invaluable.",
  "The stars align for a cozy evening. Make it special.",
  "Your next thought will spark an idea worth exploring.",
  "Someone will appreciate your kindness more than they can say.",
  "You’ll witness an unspoken bond between two people. It will warm your heart.",
  "The next thing you try for the first time will bring surprising joy.",
  "An old lesson will suddenly feel relevant again.",
  "You’ll find comfort in a simple routine today.",
  "A funny video will make you laugh harder than you expected.",
  "Your imagination will surprise you with its brilliance today.",
  "The next gift you receive will feel deeply thoughtful.",
  "A quick glance at the sky will fill you with awe.",
  "The next compliment you give will light up someone’s face.",
  "You’ll feel oddly accomplished after solving a tiny problem today.",
  "A small adventure is waiting for you—be open to it.",
  "You’ll find joy in completing a task you’ve been putting off.",
  "An unexpected message will make you feel valued today.",
  "The stars suggest you treat yourself to something sweet today.",
  "The sound of leaves rustling will bring you peace.",
  "You’ll discover a surprising connection between two unrelated things.",
  "The next snack you have will feel oddly perfect.",
  "You’ll be someone’s reason to smile today.",
  "A warm cup of something will feel like a hug today.",
  "You’ll notice a pattern in something that was random before.",
  "The next small decision you make will lead to something delightful.",
  "Someone will share good news with you that lifts your spirits.",
  "You’ll notice a flicker of magic in the mundane today.",
  "A random act of kindness will find its way to you.",
  "You’ll feel unusually bold and confident today. Ride the wave.",
  "The stars say this is a great day to try something unconventional.",
  "You’ll find the answer to a question you didn’t realize you were asking.",
  "A simple ritual today will feel especially grounding.",
  "Your next sip of water will taste like a reset button for your mind.",
  "The sound of laughter will remind you of something beautiful.",
  "An unexpected detail will turn your day around in the best way.",
  "Your perseverance will inspire someone quietly watching you.",
  "The next thing you read will open your mind to something new.",
  "You’ll notice someone’s quiet strength and admire them for it.",
  "The next smell you encounter will make you smile. Take it in.",
  "You’ll accomplish something today that you’ve been avoiding. Celebrate it.",
  "An opportunity will arise that feels like a perfect fit.",
  "The stars say this is a great day to explore. See where it takes you.",
  "You’ll laugh at something silly today and feel lighter for it.",
  "The next time you stop to breathe, it will feel unusually refreshing.",
  "A heartfelt compliment will make your day shine brighter.",
  "The next animal you see will remind you to live in the moment.",
  "Someone will quietly admire your work today. Own it.",
  "Your next piece of advice will be exactly what someone needs to hear.",
  "A spontaneous decision today will lead to a joyful surprise.",
  "You’ll discover the charm of something you once overlooked.",
  "An unusual coincidence will leave you shaking your head in wonder.",
  "The stars say today is perfect for reconnecting with an old hobby.",
  "You’ll find inspiration in something simple yet profound.",
  "The next time you catch your reflection, you’ll see your growth.",
] as const;
